### ISSUE TITLE
Twitch chat isn't loading

### ISSUE THREAD

**Issue by paulpugh000** [Nymnion/Forsen#85]
In the [embed docs](https://dev.twitch.tv/docs/embed/chat/), the URL for the iframe needs the parent site URL
Currently, `forsen.site` is being used instead of `www.forsen.site` resulting in this error:
``` 
Refused to frame 'https://www.twitch.tv/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors https://forsen.site".
```

**Comment by gempir** [comment]
Nobody said www is the correct url. Don't use www

**Comment by paulpugh000** [comment]
I see, am I having a unique problem with the embed not loading, or is there a different issue?

**Comment by gempir** [comment]
I don't understand the question. Just use https://forsen.site everything loads there

**Comment by gempir** [comment]
Yeah nymn has to force https in the settings I can't change it
